import React, { useState } from 'react';
import { ICPData } from '../types';
import { Download, Printer, Send, RotateCw, X, Sparkles, CheckCircle, AlertTriangle, Briefcase, Target, Zap, DollarSign, Activity, Flag } from 'lucide-react';
import { refineProposal } from '../services/geminiService';

interface ICPResultProps {
  data: ICPData;
  originalInput: string;
  onReset: () => void;
  onRetry: () => void;
}

export const ICPResult: React.FC<ICPResultProps> = ({ data, originalInput, onReset, onRetry }) => {
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [selectedClientEmail, setSelectedClientEmail] = useState(''); // Kept for consistency, though manually entered now
  const [selectedClientName, setSelectedClientName] = useState(''); // Track client name
  const [proposalSubject, setProposalSubject] = useState('');
  const [proposalBody, setProposalBody] = useState('');

  // Refinement State
  const [isRefining, setIsRefining] = useState(false);
  const [refinementInput, setRefinementInput] = useState('');
  const [showRefineInput, setShowRefineInput] = useState(false);

  const handlePrint = () => {
    window.print();
  };

  const handleDownloadMarkdown = () => {
    let md = `# ICP Analysis: ${data.serviceName}\n\n`;
    md += `> Generated by Cehpoint Strategic Intelligence on ${new Date().toLocaleDateString()}\n\n`;

    md += `## 1. Service Context\n${data?.serviceName || 'N/A'}\n\n`;
    md += `## 2. Target Company Profile\n- **Type**: ${data?.companyProfile?.type || 'N/A'}\n- **Size**: ${data?.companyProfile?.size || 'N/A'}\n- **Geography**: ${data?.companyProfile?.geography || 'N/A'}\n- **Industry**: ${data?.companyProfile?.industry || 'N/A'}\n\n`;

    md += `## 3. Decision-Maker Profile\n- **Primary Stakeholders**: ${data?.decisionMaker?.primary?.join(', ') || 'N/A'}\n- **Secondary Influencers**: ${data?.decisionMaker?.secondary?.join(', ') || 'N/A'}\n- **Role Focus**: ${data?.decisionMaker?.role || 'N/A'}\n\n`;

    md += `## 4. Critical Pain Points\n${(data?.painPoints || []).map(p => `- ${p}`).join('\n')}\n\n`;

    md += `## 5. Strategic Business Goals\n${(data?.businessGoals || []).map(g => `- ${g}`).join('\n')}\n\n`;

    md += `## 6. Buying Triggers\n${(data?.buyingTriggers || []).map(t => `- ${t}`).join('\n')}\n\n`;

    md += `## 7. Commercial Readiness\n- **Budget Range**: ${data?.commercialReadiness?.budgetRange || 'N/A'}\n- **Buying Model**: ${data?.commercialReadiness?.buyingModel || 'N/A'}\n- **Approval Complexity**: ${data?.commercialReadiness?.approvalComplexity || 'N/A'}\n\n`;

    md += `## 8. Technical Maturity\n- **Likely Tech Stack**: ${data?.technicalMaturity?.techStack?.join(', ') || 'N/A'}\n- **Team Capability**: ${data?.technicalMaturity?.teamStatus || 'N/A'}\n- **Data Readiness**: ${data?.technicalMaturity?.dataReadiness || 'N/A'}\n\n`;

    md += `## 9. Success Criteria (ROI)\n${(data?.successCriteria || []).map(s => `- ${s}`).join('\n')}\n\n`;

    md += `## 10. Objections & Risks\n- **Common Objections**: ${data?.objectionsAndRisks?.commonObjections?.join(', ') || 'N/A'}\n- **Risk Factors**: ${data?.objectionsAndRisks?.riskFactors?.join(', ') || 'N/A'}\n\n`;

    md += `## 11. Why Cehpoint?\n${data?.whyUs || 'N/A'}\n\n`;

    md += `## 12. Qualification Checklist\n${Object.entries(data?.qualificationChecklist || {}).map(([k, v]) => `- [${v ? 'x' : ' '}] ${k.replace(/([A-Z])/g, ' $1').trim()}`).join('\n')}\n\n`;

    md += `## 13. Engagement Model\n${data?.engagementModel || 'N/A'}\n\n`;

    md += `## 14. Red Flags (Disqualifiers)\n${(data?.redFlags || []).map(f => `- ${f}`).join('\n')}\n\n`;

    md += `## 15. Upsell Potential\n${(data?.upsellPotential || []).map(u => `- ${u}`).join('\n')}\n\n`;

    md += `## 16. High-Value Target Leads\n`;
    if (data?.potentialClients?.length) {
      data.potentialClients.forEach(c => {
        md += `### ${c.name}\n`;
        md += `- **Website**: ${c.website}\n`;
        md += `- **Contact**: ${c.contactEmail || 'N/A'}\n`;
        md += `- **Context**: ${c.description}\n\n`;
      });
    } else {
      md += `No specific leads generated.\n\n`;
    }

    md += `## 17. Masterpiece Outreach Template\n`;
    md += `**Subject**: ${data?.outreachTemplate?.subject || 'N/A'}\n\n`;
    md += `**Body**:\n${data?.outreachTemplate?.body || 'N/A'}\n\n`;

    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `ICP_${(data?.serviceName || 'Analysis').replace(/\s+/g, '_')}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const openProposalModal = (clientEmail?: string, clientName?: string) => {
    let subject = data?.outreachTemplate?.subject || 'Outreach Proposal';
    let body = data?.outreachTemplate?.body || 'Content generation failed.';

    // Personalization Logic
    if (clientName) {
      subject = subject.replace(/\[Client Name\]/gi, clientName);
      subject = subject.replace(/\[Company Name\]/gi, clientName);
      body = body.replace(/\[Client Name\]/gi, clientName);
      body = body.replace(/\[Company Name\]/gi, clientName);
    } else {
      // If no specific client, replace with generic but professional placeholder
      subject = subject.replace(/\[Client Name\]/gi, "Potential Partner");
      subject = subject.replace(/\[Company Name\]/gi, "Potential Partner");
      body = body.replace(/\[Client Name\]/gi, "Potential Partner");
      body = body.replace(/\[Company Name\]/gi, "Potential Partner");
    }

    setProposalSubject(subject);
    setProposalBody(body);
    setRefinementInput('');
    setSelectedClientEmail(clientEmail || ''); // Reset email if opened from main button
    setSelectedClientName(clientName || '');
    setShowRefineInput(false);
    setIsModalOpen(true);
  };

  const handleRefineProposal = async () => {
    if (!refinementInput.trim()) return;
    setIsRefining(true);
    try {
      const result = await refineProposal(proposalSubject, proposalBody, refinementInput, originalInput);
      setProposalSubject(result.subject);
      setProposalBody(result.body);
      setRefinementInput('');
    } catch (error) {
      console.error("Failed to refine", error);
      alert("Failed to refine proposal. Please try again.");
    } finally {
      setIsRefining(false);
    }
  };

  const handleSendMail = () => {
    if (!selectedClientEmail) {
      alert("No email address found for this client. The proposal will generate, but you need to manually enter the recipient.");
    }
    const subject = encodeURIComponent(proposalSubject);
    const body = encodeURIComponent(proposalBody);
    const mailToLink = `mailto:${selectedClientEmail}?subject=${subject}&body=${body}`;
    window.location.href = mailToLink;
    // setIsModalOpen(false); // Keep open so they can copy-paste if mailto fails length limits
  };

  return (
    <div className="w-full pb-20 relative">

      {/* Utility Toolbar */}
      <div className="flex justify-between items-center mb-8 no-print border-b border-slate-800 pb-6">
        <div className="flex gap-4">
          <button onClick={onReset} className="text-slate-400 hover:text-white font-medium text-sm transition-colors uppercase tracking-wide flex items-center gap-2">
            <span className="text-lg">←</span> New Strategy
          </button>
          <button onClick={onRetry} className="text-indigo-400 hover:text-indigo-300 font-medium text-sm transition-colors flex items-center gap-2 uppercase tracking-wide">
            <RotateCw className="w-3 h-3" /> Regenerate
          </button>
        </div>
        <div className="flex gap-3">
          <button onClick={handleDownloadMarkdown} className="flex items-center gap-2 px-4 py-2 bg-slate-900 border border-slate-700 rounded text-slate-300 text-xs font-bold uppercase tracking-wider hover:bg-slate-800 hover:text-white hover:border-slate-500 transition-all">
            <Download className="w-3 h-3" /> Export Report
          </button>
          <button onClick={handlePrint} className="flex items-center gap-2 px-4 py-2 bg-slate-200 text-slate-900 rounded text-xs font-bold uppercase tracking-wider hover:bg-white transition-all shadow-lg shadow-white/5">
            <Printer className="w-3 h-3" /> Print
          </button>
        </div>
      </div>

      <div className="print-container space-y-8">

        {/* Header Section */}
        <section className="glass-panel text-white rounded-xl p-10 relative overflow-hidden">
          <div className="absolute top-0 right-0 w-64 h-64 bg-indigo-500/10 rounded-full blur-3xl -mr-20 -mt-20"></div>
          <h1 className="text-4xl font-serif font-bold mb-2 relative z-10">{data?.serviceName || 'Strategic Analysis'}</h1>
          <div className="w-20 h-1 bg-amber-500 mb-8 relative z-10"></div>

          <div className="grid grid-cols-2 md:grid-cols-4 gap-8 text-sm relative z-10 border-t border-slate-700/50 pt-8">
            <div>
              <span className="block text-slate-400 text-[10px] uppercase tracking-[0.2em] mb-2">Structure</span>
              <span className="font-semibold text-lg text-slate-100">{data?.companyProfile?.type || 'N/A'}</span>
            </div>
            <div>
              <span className="block text-slate-400 text-[10px] uppercase tracking-[0.2em] mb-2">Scale</span>
              <span className="font-semibold text-lg text-slate-100">{data?.companyProfile?.size || 'N/A'}</span>
            </div>
            <div>
              <span className="block text-slate-400 text-[10px] uppercase tracking-[0.2em] mb-2">Region</span>
              <span className="font-semibold text-lg text-slate-100">{data?.companyProfile?.geography || 'N/A'}</span>
            </div>
            <div>
              <span className="block text-slate-400 text-[10px] uppercase tracking-[0.2em] mb-2">Sector</span>
              <span className="font-semibold text-lg text-slate-100">{data?.companyProfile?.industry || 'N/A'}</span>
            </div>
          </div>
        </section>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          {/* Box 3: Decision Maker */}
          <div className="glass-panel p-8 rounded-xl border-l-4 border-l-blue-500">
            <h3 className="flex items-center gap-2 font-bold text-blue-400 mb-6 uppercase text-xs tracking-[0.2em]">
              <Briefcase className="w-4 h-4" /> Decision Metrics
            </h3>
            <div className="space-y-4 text-sm">
              <div className="pb-3 border-b border-slate-700/50">
                <span className="text-slate-400 block text-xs uppercase mb-1">Primary Stakeholders</span>
                <span className="text-white text-lg font-medium">{data?.decisionMaker?.primary?.join(', ') || 'N/A'}</span>
              </div>
              <div className="pb-3 border-b border-slate-700/50">
                <span className="text-slate-400 block text-xs uppercase mb-1">Secondary Influencers</span>
                <span className="text-slate-300">{data?.decisionMaker?.secondary?.join(', ') || 'N/A'}</span>
              </div>
              <div>
                <span className="text-slate-400 block text-xs uppercase mb-1">Role Focus</span>
                <span className="text-slate-300 italic">"{data?.decisionMaker?.role || 'N/A'}"</span>
              </div>
            </div>
          </div>

          {/* Box 4 & 5: Pain Points & Goals */}
          <div className="glass-panel p-8 rounded-xl border-l-4 border-l-red-500">
            <h3 className="flex items-center gap-2 font-bold text-red-400 mb-6 uppercase text-xs tracking-[0.2em]">
              <Target className="w-4 h-4" /> Critical Drivers
            </h3>
            <div className="grid grid-cols-1 gap-6 text-sm">
              <div>
                <h4 className="font-bold text-white mb-3 flex items-center gap-2 text-xs uppercase opacity-80">
                  Operational Friction (Pain Points)
                </h4>
                <ul className="space-y-2">
                  {(data?.painPoints || []).slice(0, 3).map((p, i) => (
                    <li key={i} className="flex gap-3 text-slate-300">
                      <span className="text-red-500 mt-1">●</span>
                      <span>{p}</span>
                    </li>
                  ))}
                </ul>
              </div>
              <div className="pt-4 border-t border-slate-700/50">
                <h4 className="font-bold text-white mb-3 flex items-center gap-2 text-xs uppercase opacity-80">
                  Strategic Objectives
                </h4>
                <ul className="space-y-2">
                  {(data?.businessGoals || []).slice(0, 3).map((g, i) => (
                    <li key={i} className="flex gap-3 text-slate-300">
                      <span className="text-emerald-500 mt-1">●</span>
                      <span>{g}</span>
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          </div>
        </div>

        {/* Commercial & Technical (Grid) */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          {/* 7. Commercial */}
          <div className="glass-panel p-8 rounded-xl">
            <h3 className="flex items-center gap-2 font-bold text-emerald-400 mb-6 uppercase text-xs tracking-[0.2em]">
              <DollarSign className="w-4 h-4" /> Commercial
            </h3>
            <ul className="space-y-4 text-sm">
              <li>
                <span className="block text-slate-500 text-[10px] uppercase">Budget Range</span>
                <span className="font-mono text-white text-lg">{data?.commercialReadiness?.budgetRange || 'N/A'}</span>
              </li>
              <li>
                <span className="block text-slate-500 text-[10px] uppercase">Model</span>
                <span className="text-slate-300">{data?.commercialReadiness?.buyingModel || 'N/A'}</span>
              </li>
              <li>
                <span className="block text-slate-500 text-[10px] uppercase">Complexity</span>
                <span className={`inline-block mt-1 px-2 py-0.5 rounded text-[10px] font-bold uppercase tracking-wider ${data?.commercialReadiness?.approvalComplexity === 'High' ? 'bg-red-900/50 text-red-200 border border-red-800' : 'bg-green-900/50 text-green-200 border border-green-800'}`}>
                  {data?.commercialReadiness?.approvalComplexity || 'N/A'}
                </span>
              </li>
            </ul>
          </div>

          {/* 8. Technical */}
          <div className="glass-panel p-8 rounded-xl">
            <h3 className="flex items-center gap-2 font-bold text-amber-400 mb-6 uppercase text-xs tracking-[0.2em]">
              <Zap className="w-4 h-4" /> Tech Maturity
            </h3>
            <ul className="space-y-4 text-sm">
              <li>
                <span className="block text-slate-500 text-[10px] uppercase">Team Capability</span>
                <span className="text-white font-medium">{data?.technicalMaturity?.teamStatus || 'N/A'}</span>
              </li>
              <li>
                <span className="block text-slate-500 text-[10px] uppercase">Data Readiness</span>
                <span className="text-white font-medium">{data?.technicalMaturity?.dataReadiness || 'N/A'}</span>
              </li>
              <li className="pt-2">
                <span className="block text-slate-500 text-[10px] uppercase mb-2">Likely Stack</span>
                <div className="flex flex-wrap gap-2">
                  {data?.technicalMaturity?.techStack?.map((stack, i) => (
                    <span key={i} className="font-mono text-[10px] bg-slate-800 border border-slate-600 text-slate-300 px-2 py-1 rounded">
                      {stack}
                    </span>
                  )) || 'N/A'}
                </div>
              </li>
            </ul>
          </div>

          {/* 13. Engagement */}
          <div className="glass-panel p-8 rounded-xl flex flex-col justify-center text-center relative overflow-hidden">
            <div className="absolute inset-0 bg-indigo-500/5"></div>
            <h3 className="font-bold text-indigo-400 mb-6 uppercase text-xs tracking-[0.2em] relative z-10">
              Engagement Model
            </h3>
            <div className="relative z-10">
              <div className="text-2xl font-serif font-bold text-white mb-2">{data?.engagementModel || 'N/A'}</div>
              <div className="text-[10px] text-slate-500 uppercase tracking-widest">Recommended Approach</div>
            </div>
          </div>
        </div>

        {/* 12. Qualification Checklist */}
        <div className="glass-panel p-8 rounded-xl border border-slate-700/50">
          <h3 className="flex items-center gap-2 font-bold text-emerald-400 mb-8 uppercase text-xs tracking-[0.2em]">
            <CheckCircle className="w-4 h-4" /> Qualification Confidence
          </h3>
          <div className="grid grid-cols-2 md:grid-cols-5 gap-6">
            {Object.entries(data?.qualificationChecklist || {}).map(([key, value]) => (
              <div key={key} className="flex flex-col items-center p-4 bg-slate-800/50 rounded border border-slate-700 hover:border-slate-500 transition-colors">
                <div className={`w-8 h-8 rounded-full flex items-center justify-center mb-3 shadow-lg ${value ? 'bg-emerald-500/20 text-emerald-400' : 'bg-red-500/20 text-red-400'}`}>
                  {value ? <CheckCircle className="w-5 h-5" /> : <X className="w-5 h-5" />}
                </div>
                <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider text-center">{key.replace(/([A-Z])/g, ' $1').trim()}</span>
              </div>
            ))}
          </div>
        </div>

        {/* 10, 11, 14, 15: Risks & Opportunities */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          <div className="glass-panel p-8 rounded-xl">
            <h3 className="font-bold text-slate-300 mb-6 uppercase text-xs tracking-[0.2em]">Objections & Risks</h3>
            <div className="space-y-6 text-sm">
              <div>
                <span className="text-slate-500 font-bold block mb-2 text-xs uppercase">Key Objections</span>
                <p className="text-slate-300 leading-relaxed">{data?.objectionsAndRisks?.commonObjections?.join(', ') || 'N/A'}</p>
              </div>
              <div>
                <span className="text-red-400 font-bold block mb-2 text-xs uppercase">Disqualifiers (Red Flags)</span>
                <ul className="list-none space-y-1">
                  {(data?.redFlags || []).map((f, i) => (
                    <li key={i} className="text-red-300/80 flex gap-2">
                      <span className="text-red-500">-</span> {f}
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          </div>
          <div className="glass-panel p-8 rounded-xl bg-gradient-to-br from-slate-900 to-indigo-950/30">
            <h3 className="font-bold text-amber-400 mb-6 uppercase text-xs tracking-[0.2em]">Winning Strategy</h3>
            <div className="space-y-6 text-sm">
              <div>
                <span className="text-indigo-300 font-bold block mb-2 text-xs uppercase">The USP Match</span>
                <p className="text-slate-200 leading-relaxed font-serif italic text-lg opacity-90">"{data?.whyUs || 'N/A'}"</p>
              </div>
              <div>
                <span className="text-emerald-400 font-bold block mb-2 text-xs uppercase">Expansion Potential</span>
                <span className="text-slate-300 border-b border-emerald-500/30 pb-1">{data?.upsellPotential?.join(', ') || 'N/A'}</span>
              </div>
            </div>
          </div>
        </div>

        {/* 16. Potential Leads (New Section) */}
        {data?.potentialClients && data.potentialClients.length > 0 && (
          <div className="glass-panel p-10 rounded-xl relative overflow-hidden border border-amber-500/20">
            <div className="absolute top-0 right-0 w-full h-1 bg-gradient-to-r from-transparent via-amber-500/50 to-transparent"></div>
            <h3 className="flex items-center gap-3 font-bold text-amber-500 mb-8 uppercase text-sm tracking-[0.2em]">
              <Briefcase className="w-5 h-5" /> High-Value Targets
            </h3>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              {data.potentialClients.map((client, i) => (
                <div key={i} className="group bg-slate-900/50 p-6 rounded border border-slate-700 hover:border-amber-500/50 hover:bg-slate-800 transition-all duration-300 flex flex-col justify-between hover:shadow-[0_0_20px_rgba(251,191,36,0.1)]">
                  <div>
                    <h4 className="font-serif font-bold text-xl text-white mb-2 group-hover:text-amber-400 transition-colors">{client.name}</h4>
                    <a href={client.website} target="_blank" rel="noopener noreferrer" className="text-blue-400 text-xs hover:underline mb-2 block truncate font-mono opacity-70 group-hover:opacity-100">{client.website}</a>
                    <span className="text-[10px] text-slate-500 mb-4 block uppercase tracking-wider">{client.contactEmail || 'Connect via LinkedIn'}</span>
                    <p className="text-slate-400 text-sm leading-relaxed mb-6 border-l-2 border-slate-700 pl-3">{client.description}</p>
                  </div>
                  <button
                    onClick={() => {
                      setSelectedClientEmail(client.contactEmail || '');
                      openProposalModal(client.contactEmail, client.name);
                    }}
                    className="w-full flex items-center justify-center gap-2 px-4 py-3 bg-indigo-600/20 text-indigo-300 border border-indigo-500/30 text-xs font-bold uppercase tracking-wider rounded hover:bg-indigo-600 hover:text-white hover:border-indigo-500 transition-all"
                  >
                    <Send className="w-3 h-3" /> Initiate Outreach
                  </button>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Proposal Action */}
        <div className="mt-12 flex justify-center no-print">
          <button
            onClick={() => openProposalModal()}
            className="flex items-center gap-3 px-10 py-5 bg-white text-slate-900 font-bold rounded-lg shadow-[0_0_30px_rgba(255,255,255,0.1)] hover:shadow-[0_0_50px_rgba(255,255,255,0.2)] transform hover:-translate-y-1 transition-all uppercase tracking-widest text-sm"
          >
            <Send className="w-4 h-4" /> View Masterpiece Proposal
          </button>
        </div>

      </div>

      {/* PROPOSAL MODAL */}
      {isModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-sm p-4 print:hidden animate-fade-in">
          <div className="bg-slate-900 rounded-xl shadow-2xl w-full max-w-3xl overflow-hidden flex flex-col max-h-[90vh] border border-slate-700">
            <div className="px-8 py-6 border-b border-slate-800 flex justify-between items-center bg-slate-900">
              <h3 className="font-serif font-bold text-white text-xl flex items-center gap-3">
                <span className="text-indigo-500">❖</span> Strategic Proposal Draft
              </h3>
              <button onClick={() => setIsModalOpen(false)} className="text-slate-500 hover:text-white transition-colors">
                <X className="w-6 h-6" />
              </button>
            </div>

            <div className="p-8 overflow-y-auto flex-grow bg-slate-950/50">
              <div className="mb-6">
                <label className="block text-[10px] font-bold text-slate-500 uppercase tracking-widest mb-2">Subject Line</label>
                <input
                  type="text"
                  value={proposalSubject}
                  onChange={(e) => setProposalSubject(e.target.value)}
                  className="w-full bg-slate-900 border border-slate-700 rounded p-4 text-sm text-white focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500/50 outline-none transition-all placeholder-slate-600"
                />
              </div>

              <div className="mb-6 flex-grow">
                <label className="block text-[10px] font-bold text-slate-500 uppercase tracking-widest mb-2">Message Content</label>
                <textarea
                  value={proposalBody}
                  onChange={(e) => setProposalBody(e.target.value)}
                  className="w-full h-96 bg-slate-900 border border-slate-700 rounded p-6 text-sm text-slate-300 font-sans focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500/50 outline-none resize-none leading-relaxed"
                />
              </div>

              {/* REFINEMENT SECTION */}
              <div className="border border-indigo-500/20 rounded bg-indigo-900/10 p-5">
                <button onClick={() => setShowRefineInput(!showRefineInput)} className="flex items-center gap-2 text-indigo-400 font-bold text-xs uppercase tracking-widest hover:text-indigo-300 transition-colors">
                  <Sparkles className="w-4 h-4" /> {showRefineInput ? 'Close Refinement' : 'Refine with AI'}
                </button>

                {showRefineInput && (
                  <div className="mt-4 animate-fade-in-up">
                    <textarea
                      placeholder="Ex: Make it more aggressive, focus on ROI..."
                      className="w-full p-4 text-sm border border-slate-700 rounded bg-slate-900 text-white focus:outline-none focus:border-indigo-500 min-h-[100px]"
                      value={refinementInput}
                      onChange={(e) => setRefinementInput(e.target.value)}
                    />
                    <div className="mt-3 flex justify-end">
                      <button
                        onClick={handleRefineProposal}
                        disabled={isRefining || !refinementInput.trim()}
                        className="px-6 py-2 bg-indigo-600 text-white rounded text-xs font-bold uppercase tracking-wider hover:bg-indigo-500 disabled:opacity-50 transition-all"
                      >
                        {isRefining ? 'Optimizing...' : 'Apply Improvements'}
                      </button>
                    </div>
                  </div>
                )}
              </div>

            </div>

            <div className="px-8 py-6 border-t border-slate-800 bg-slate-900 flex justify-end gap-3">
              <button
                onClick={handleSendMail}
                className="px-8 py-3 bg-white text-slate-900 text-xs font-bold uppercase tracking-widest rounded hover:bg-slate-200 shadow-lg shadow-white/5 flex items-center gap-2 transition-all"
              >
                <Send className="w-4 h-4" /> Launch Mail Client
              </button>
            </div>
          </div>
        </div>
      )}

    </div>
  );
};